-- CreateTable
CREATE TABLE "overview" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "type" INTEGER NOT NULL,
    "x" INTEGER NOT NULL,
    "y" INTEGER NOT NULL,
    "w" INTEGER NOT NULL,
    "h" INTEGER NOT NULL,
    "data" TEXT NOT NULL,
    "deleted_at" INTEGER NOT NULL DEFAULT 0
);
