CREATE TABLE IF NOT EXISTS plan (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  deleted_at TIMESTAMP DEFAULT 0,
  UNIQUE (name, deleted_at),
  UNIQUE (color, deleted_at)
);

CREATE TABLE IF NOT EXISTS note (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  description TEXT,
  deleted_at TIMESTAMP DEFAULT 0,
  plan_id INTEGER NOT NULL,
  FOREIGN KEY (plan_id) REFERENCES plan (id)
);

CREATE TABLE IF NOT EXISTS label (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  deleted_at TIMESTAMP DEFAULT 0,
  plan_id INTEGER NOT NULL,
  FOREIGN KEY (plan_id) REFERENCES plan (id),
  UNIQUE (name, deleted_at)
);

CREATE TABLE IF NOT EXISTS note_label (
  note_id INTEGER NOT NULL REFERENCES note (id),
  label_id INTEGER NOT NULL REFERENCES label (id)
);
