//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0-rc.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dimension")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub deleted_at: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dimension_label::Entity")]
    DimensionLabel,
    #[sea_orm(has_many = "super::dimension_program::Entity")]
    DimensionProgram,
}

impl Related<super::dimension_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionLabel.def()
    }
}

impl Related<super::dimension_program::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionProgram.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
