//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0-rc.1

pub mod prelude;

pub mod activity;
pub mod r#box;
pub mod domain;
pub mod history;
pub mod label;
pub mod link;
pub mod moment;
pub mod note;
pub mod overview;
pub mod plan;
pub mod program;
pub mod remark;
