//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0-rc.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "overview")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub r#type: i64,
    pub x: i64,
    pub y: i64,
    pub w: i64,
    pub h: i64,
    #[sea_orm(column_type = "Text")]
    pub data: String,
    pub deleted_at: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
