//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0-rc.1

// pub use super::activity::Entity as Activity;
// pub use super::domain::Entity as Domain;
// pub use super::history::Entity as History;
// pub use super::label::Entity as Label;
// pub use super::link::Entity as Link;
// pub use super::moment::Entity as Moment;
// pub use super::note::Entity as Note;
// pub use super::overview::Entity as Overview;
// pub use super::plan::Entity as Plan;
pub use super::program::Entity as Program;
// pub use super::r#box::Entity as Box;
// pub use super::remark::Entity as Remark;
