// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalendarGraph: typeof import('./components/CalendarGraph.vue')['default']
    InsertRecord: typeof import('./components/InsertRecord.vue')['default']
    RecordForm: typeof import('./components/RecordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateRecord: typeof import('./components/UpdateRecord.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VFadeTransition: typeof import('vuetify/components')['VFadeTransition']
    VForm: typeof import('vuetify/components')['VForm']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTextField: typeof import('vuetify/components')['VTextField']
    VTooltip: typeof import('vuetify/components')['VTooltip']
  }
}
