// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalendarGraph: typeof import('./components/CalendarGraph.vue')['default']
    Confirm: typeof import('./components/Confirm.vue')['default']
    DialogProvider: typeof import('./components/DialogProvider.vue')['default']
    Empty: typeof import('./components/Empty.vue')['default']
    InsertLabel: typeof import('./components/InsertLabel.vue')['default']
    InsertRecord: typeof import('./components/InsertRecord.vue')['default']
    LabelForm: typeof import('./components/LabelForm.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    RecordForm: typeof import('./components/RecordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateLabel: typeof import('./components/UpdateLabel.vue')['default']
    UpdateRecord: typeof import('./components/UpdateRecord.vue')['default']
    Upgrade: typeof import('./components/Upgrade.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VFadeTransition: typeof import('vuetify/components')['VFadeTransition']
    VForm: typeof import('vuetify/components')['VForm']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VMain: typeof import('vuetify/components')['VMain']
    VMenu: typeof import('vuetify/components')['VMenu']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/components')['VProgressLinear']
    VSelect: typeof import('vuetify/components')['VSelect']
    VTextField: typeof import('vuetify/components')['VTextField']
    VTimeline: typeof import('vuetify/components')['VTimeline']
    VTimelineItem: typeof import('vuetify/components')['VTimelineItem']
    VTooltip: typeof import('vuetify/components')['VTooltip']
  }
}
