/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./components/dialog/AboutDialog.vue')['default']
    Calendar: typeof import('./components/timeline/calendar/Calendar.vue')['default']
    CalendarMonth: typeof import('./components/timeline/calendar/CalendarMonth.vue')['default']
    ColorPickerButton: typeof import('./components/form/ColorPickerButton.vue')['default']
    ConfirmModal: typeof import('./components/modal/ConfirmModal.vue')['default']
    Empty: typeof import('./components/shared/Empty.vue')['default']
    FormFactory: typeof import('./components/form/FormFactory.vue')['default']
    FormModal: typeof import('./components/modal/FormModal.vue')['default']
    LayoutFooter: typeof import('./components/layout/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./components/layout/LayoutHeader.vue')['default']
    LayoutMain: typeof import('./components/layout/LayoutMain.vue')['default']
    LayoutNav: typeof import('./components/layout/LayoutNav.vue')['default']
    LayoutProvider: typeof import('./components/layout/LayoutProvider.vue')['default']
    MilkdownEditor: typeof import('./components/shared/MilkdownEditor.vue')['default']
    MomentEdit: typeof import('./components/moment/MomentEdit.vue')['default']
    MoreMenu: typeof import('./components/menu/MoreMenu.vue')['default']
    NavAction: typeof import('./components/nav/NavAction.vue')['default']
    NoteUpdate: typeof import('./components/note/NoteUpdate.vue')['default']
    NotificationContainer: typeof import('./components/notification/NotificationContainer.vue')['default']
    OverviewChart: typeof import('./components/overview/OverviewChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDialog: typeof import('./components/dialog/SettingDialog.vue')['default']
    TitleBar: typeof import('./components/header/TitleBar.vue')['default']
    VAlert: typeof import('vuetify/components')['VAlert']
    VBtn: typeof import('vuetify/components')['VBtn']
    VBtnToggle: typeof import('vuetify/components')['VBtnToggle']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VCheckboxBtn: typeof import('vuetify/components')['VCheckboxBtn']
    VColorPicker: typeof import('vuetify/components')['VColorPicker']
    VDialog: typeof import('vuetify/components')['VDialog']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemAction: typeof import('vuetify/components')['VListItemAction']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VLocaleProvider: typeof import('vuetify/components')['VLocaleProvider']
    VMenu: typeof import('vuetify/components')['VMenu']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTextField: typeof import('vuetify/components')['VTextField']
    VThemeProvider: typeof import('vuetify/components')['VThemeProvider']
    VTooltip: typeof import('vuetify/components')['VTooltip']
  }
}
