/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./components/dialog/AboutDialog.vue')['default']
    ActiveStatusCalendar: typeof import('./components/widget/ActiveStatusCalendar.vue')['default']
    Calendar: typeof import('./components/timeline/calendar/Calendar.vue')['default']
    CalendarMonth: typeof import('./components/timeline/calendar/CalendarMonth.vue')['default']
    Cascader: typeof import('./components/form/Cascader.vue')['default']
    ColorPicker: typeof import('./components/form/ColorPicker.vue')['default']
    ConfirmModal: typeof import('./components/modal/ConfirmModal.vue')['default']
    Empty: typeof import('./components/shared/Empty.vue')['default']
    FooterTeleport: typeof import('./components/footer/FooterTeleport.vue')['default']
    FormFactory: typeof import('./components/form/FormFactory.vue')['default']
    FormModal: typeof import('./components/modal/FormModal.vue')['default']
    Grid: typeof import('./components/grid/Grid.vue')['default']
    GridCard: typeof import('./components/grid/GridCard.vue')['default']
    LayoutFooter: typeof import('./components/layout/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./components/layout/LayoutHeader.vue')['default']
    LayoutMain: typeof import('./components/layout/LayoutMain.vue')['default']
    LayoutNav: typeof import('./components/layout/LayoutNav.vue')['default']
    LayoutProvider: typeof import('./components/layout/LayoutProvider.vue')['default']
    MomentEdit: typeof import('./components/moment/MomentEdit.vue')['default']
    MoreMenu: typeof import('./components/menu/MoreMenu.vue')['default']
    NavAction: typeof import('./components/nav/NavAction.vue')['default']
    NestedMenu: typeof import('./components/shared/NestedMenu.vue')['default']
    NotificationContainer: typeof import('./components/notification/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDialog: typeof import('./components/dialog/SettingDialog.vue')['default']
    SingleCategoryBar: typeof import('./components/widget/SingleCategoryBar.vue')['default']
    StatusBar: typeof import('./components/footer/StatusBar.vue')['default']
    TextSummary: typeof import('./components/widget/TextSummary.vue')['default']
    TimeCard: typeof import('./components/widget/TimeCard.vue')['default']
    TimelineFilter: typeof import('./components/timeline/TimelineFilter.vue')['default']
    TimelineGraph: typeof import('./components/timeline/TimelineGraph.vue')['default']
    Tiptap: typeof import('./components/shared/Tiptap.vue')['default']
    TitleBar: typeof import('./components/header/TitleBar.vue')['default']
    TooltipButton: typeof import('./components/shared/TooltipButton.vue')['default']
  }
}
