// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InsertTime(arg1:string):Promise<void>;

export function SelectAllTime():Promise<Array<main.Time>>;
