// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InsertTime(arg1) {
  return window['go']['main']['App']['InsertTime'](arg1);
}

export function SelectAllTime() {
  return window['go']['main']['App']['SelectAllTime']();
}
